### ISSUE TITLE
Improve discoverability

### ISSUE THREAD

**Issue by fzaninotto** [dreinke/aor-color-input#1]
Hi, 

Congrats for the lib!

To improve discoverability I advise you to:

- add the `admin-on-rest` label to your repository
- make a PR against the admin-on-rest `doc/Inputs.md` page to mention your custom input.

**Comment by dreinke** [comment]
Hi @fzaninotto,
Thanks for the advice!
Should I make the PR directly to the branch `next`?

**Comment by fzaninotto** [comment]
`next` will be merged to `master` in a few hours. Then you can open a PR on `master`.
