### ISSUE TITLE
addComponentAsRefTo error

### ISSUE THREAD

**Issue by rigobcastro** [dreinke/aor-color-input#2]
The next error appears when I'm trying to use this:

`
addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
`

admin-on-rest: v1.1.1

**Comment by dreinke** [comment]
Hey @rigobcastro!
Thanks for the report and I'm so sorry for the delay. Hope you have already found a solution.
Try to update your aor-color-input version. I fixed a problem with the dependencies. :wink:
