### ISSUE TITLE
PropTypes is undefined

### ISSUE THREAD

**Issue by SamiSammour** [dreinke/aor-color-input#3]
I am using your component in my React 16 app and it gives me "PropTypes is undefined" because it has been moved to a separate module.
Can you please supply a build using the stand alone 'prop-types' package?

**Comment by samhiddenhand** [comment]
I'm having the exact same problem.

**Comment by dreinke** [comment]
Thanks for the report, @SamiSammour!
The issue has been fixed in the latest release (v1.1.3).
